(defpackage #:valtheradb-conduit
  (:use #:cl)
  (:export #:conduit
           #:make-conduit
           #:conduit-ready
           #:conduit-shutdown
           #:conduit-close
           #:db
           #:make-db
           #:db-init
           #:db-execute
           #:db-collection
           #:db-get-collections
           #:db-ensure-collection
           #:db-isset-collection
           #:db-remove-collection
           #:db-add
           #:db-find
           #:db-find-one
           #:db-update
           #:db-update-one
           #:db-remove
           #:db-remove-one
           #:db-update-one-or-add
           #:db-toggle-one
           #:db-close
           #:collection
           #:make-collection
           #:collection-add
           #:collection-find
           #:collection-find-one
           #:collection-update
           #:collection-update-one
           #:collection-remove
           #:collection-remove-one
           #:collection-update-one-or-add
           #:collection-toggle-one
           #:conduit-error
           #:conduit-error-code
           #:conduit-error-message))
