(in-package #:valtheradb-conduit)

(defconstant +header-size+ 12)
(defconstant +init-db+ 1)
(defconstant +execute-json+ 2)
(defconstant +close-db+ 3)
(defconstant +list-dbs+ 4)
(defconstant +ping+ 5)
(defconstant +shutdown+ 6)
(defconstant +ready+ 100)
(defconstant +result+ 101)
(defconstant +error+ 102)
(defconstant +pong+ 104)

(defun encode-frame (frame-type db-name payload)
  (let* ((db-bytes (flexi-streams:string-to-octets (or db-name "") :external-format :utf-8))
         (payload-bytes (flexi-streams:string-to-octets
                         (json:encode-json-to-string (or payload (make-hash-table)))
                         :external-format :utf-8))
         (buf (make-array (+ +header-size+ (length db-bytes) (length payload-bytes))
                          :element-type '(unsigned-byte 8))))
    (setf (nibbles:ub32ref/le buf 0) frame-type)
    (setf (nibbles:ub32ref/le buf 4) (length db-bytes))
    (setf (nibbles:ub32ref/le buf 8) (length payload-bytes))
    (replace buf db-bytes :start1 +header-size+)
    (replace buf payload-bytes :start1 (+ +header-size+ (length db-bytes)))
    buf))

(defun read-exact (stream count)
  (let ((buf (make-array count :element-type '(unsigned-byte 8))))
    (loop for offset = 0 then (+ offset n)
          for n = (read-sequence buf stream :start offset)
          while (< (+ offset n) count)
          when (= n 0) do (error 'end-of-file :stream stream))
    buf))

(defun read-frame (stream)
  (let* ((header (read-exact stream +header-size+))
         (frame-type (nibbles:ub32ref/le header 0))
         (db-name-len (nibbles:ub32ref/le header 4))
         (payload-len (nibbles:ub32ref/le header 8))
         (db-name (if (> db-name-len 0)
                      (flexi-streams:octets-to-string (read-exact stream db-name-len) :external-format :utf-8)
                      ""))
         (payload (if (> payload-len 0)
                      (json:decode-json-from-string
                       (flexi-streams:octets-to-string (read-exact stream payload-len) :external-format :utf-8))
                      (make-hash-table))))
    (list :frame-type frame-type :db-name db-name :payload payload)))
